import { BeepBoxOption, DictionaryArray } from "../synth/SynthConfig";
import { Song } from "../synth/synth";
export interface ChannelColors extends BeepBoxOption {
    readonly secondaryChannel: string;
    readonly primaryChannel: string;
    readonly secondaryNote: string;
    readonly primaryNote: string;
}
export declare class ColorConfig {
    static colorLookup: Map<number, ChannelColors>;
    static usesColorFormula: boolean;
    static readonly themes: {
        [name: string]: string;
    };
    static readonly pageMargin: string;
    static readonly editorBackground: string;
    static readonly hoverPreview: string;
    static readonly playhead: string;
    static readonly primaryText: string;
    static readonly secondaryText: string;
    static readonly invertedText: string;
    static readonly textSelection: string;
    static readonly boxSelectionFill: string;
    static readonly loopAccent: string;
    static readonly linkAccent: string;
    static readonly uiWidgetBackground: string;
    static readonly uiWidgetFocus: string;
    static readonly pitchBackground: string;
    static readonly tonic: string;
    static readonly fifthNote: string;
    static readonly whitePianoKey: string;
    static readonly blackPianoKey: string;
    static readonly useColorFormula: string;
    static readonly pitchSecondaryChannelHue: string;
    static readonly pitchSecondaryChannelHueScale: string;
    static readonly pitchSecondaryChannelSat: string;
    static readonly pitchSecondaryChannelSatScale: string;
    static readonly pitchSecondaryChannelLum: string;
    static readonly pitchSecondaryChannelLumScale: string;
    static readonly pitchPrimaryChannelHue: string;
    static readonly pitchPrimaryChannelHueScale: string;
    static readonly pitchPrimaryChannelSat: string;
    static readonly pitchPrimaryChannelSatScale: string;
    static readonly pitchPrimaryChannelLum: string;
    static readonly pitchPrimaryChannelLumScale: string;
    static readonly pitchSecondaryNoteHue: string;
    static readonly pitchSecondaryNoteHueScale: string;
    static readonly pitchSecondaryNoteSat: string;
    static readonly pitchSecondaryNoteSatScale: string;
    static readonly pitchSecondaryNoteLum: string;
    static readonly pitchSecondaryNoteLumScale: string;
    static readonly pitchPrimaryNoteHue: string;
    static readonly pitchPrimaryNoteHueScale: string;
    static readonly pitchPrimaryNoteSat: string;
    static readonly pitchPrimaryNoteSatScale: string;
    static readonly pitchPrimaryNoteLum: string;
    static readonly pitchPrimaryNoteLumScale: string;
    static readonly modSecondaryChannelHue: string;
    static readonly modSecondaryChannelHueScale: string;
    static readonly modSecondaryChannelSat: string;
    static readonly modSecondaryChannelSatScale: string;
    static readonly modSecondaryChannelLum: string;
    static readonly modSecondaryChannelLumScale: string;
    static readonly modPrimaryChannelHue: string;
    static readonly modPrimaryChannelHueScale: string;
    static readonly modPrimaryChannelSat: string;
    static readonly modPrimaryChannelSatScale: string;
    static readonly modPrimaryChannelLum: string;
    static readonly modPrimaryChannelLumScale: string;
    static readonly modSecondaryNoteHue: string;
    static readonly modSecondaryNoteHueScale: string;
    static readonly modSecondaryNoteSat: string;
    static readonly modSecondaryNoteSatScale: string;
    static readonly modSecondaryNoteLum: string;
    static readonly modSecondaryNoteLumScale: string;
    static readonly modPrimaryNoteHue: string;
    static readonly modPrimaryNoteHueScale: string;
    static readonly modPrimaryNoteSat: string;
    static readonly modPrimaryNoteSatScale: string;
    static readonly modPrimaryNoteLum: string;
    static readonly modPrimaryNoteLumScale: string;
    static readonly noiseSecondaryChannelHue: string;
    static readonly noiseSecondaryChannelHueScale: string;
    static readonly noiseSecondaryChannelSat: string;
    static readonly noiseSecondaryChannelSatScale: string;
    static readonly noiseSecondaryChannelLum: string;
    static readonly noiseSecondaryChannelLumScale: string;
    static readonly noisePrimaryChannelHue: string;
    static readonly noisePrimaryChannelHueScale: string;
    static readonly noisePrimaryChannelSat: string;
    static readonly noisePrimaryChannelSatScale: string;
    static readonly noisePrimaryChannelLum: string;
    static readonly noisePrimaryChannelLumScale: string;
    static readonly noiseSecondaryNoteHue: string;
    static readonly noiseSecondaryNoteHueScale: string;
    static readonly noiseSecondaryNoteSat: string;
    static readonly noiseSecondaryNoteSatScale: string;
    static readonly noiseSecondaryNoteLum: string;
    static readonly noiseSecondaryNoteLumScale: string;
    static readonly noisePrimaryNoteHue: string;
    static readonly noisePrimaryNoteHueScale: string;
    static readonly noisePrimaryNoteSat: string;
    static readonly noisePrimaryNoteSatScale: string;
    static readonly noisePrimaryNoteLum: string;
    static readonly noisePrimaryNoteLumScale: string;
    static readonly trackEditorBgPitch: string;
    static readonly trackEditorBgPitchDim: string;
    static readonly trackEditorBgNoise: string;
    static readonly trackEditorBgNoiseDim: string;
    static readonly trackEditorBgMod: string;
    static readonly trackEditorBgModDim: string;
    static readonly multiplicativeModSlider: string;
    static readonly overwritingModSlider: string;
    static readonly indicatorPrimary: string;
    static readonly indicatorSecondary: string;
    static readonly select2OptGroup: string;
    static readonly inputBoxOutline: string;
    static readonly muteButtonNormal: string;
    static readonly muteButtonMod: string;
    static readonly modLabelPrimary: string;
    static readonly modLabelSecondaryText: string;
    static readonly modLabelPrimaryText: string;
    static readonly disabledNotePrimary: string;
    static readonly disabledNoteSecondary: string;
    static c_pitchSecondaryChannelHue: number;
    static c_pitchSecondaryChannelHueScale: number;
    static c_pitchSecondaryChannelSat: number;
    static c_pitchSecondaryChannelSatScale: number;
    static c_pitchSecondaryChannelLum: number;
    static c_pitchSecondaryChannelLumScale: number;
    static c_pitchPrimaryChannelHue: number;
    static c_pitchPrimaryChannelHueScale: number;
    static c_pitchPrimaryChannelSat: number;
    static c_pitchPrimaryChannelSatScale: number;
    static c_pitchPrimaryChannelLum: number;
    static c_pitchPrimaryChannelLumScale: number;
    static c_pitchSecondaryNoteHue: number;
    static c_pitchSecondaryNoteHueScale: number;
    static c_pitchSecondaryNoteSat: number;
    static c_pitchSecondaryNoteSatScale: number;
    static c_pitchSecondaryNoteLum: number;
    static c_pitchSecondaryNoteLumScale: number;
    static c_pitchPrimaryNoteHue: number;
    static c_pitchPrimaryNoteHueScale: number;
    static c_pitchPrimaryNoteSat: number;
    static c_pitchPrimaryNoteSatScale: number;
    static c_pitchPrimaryNoteLum: number;
    static c_pitchPrimaryNoteLumScale: number;
    static c_modSecondaryChannelHue: number;
    static c_modSecondaryChannelHueScale: number;
    static c_modSecondaryChannelSat: number;
    static c_modSecondaryChannelSatScale: number;
    static c_modSecondaryChannelLum: number;
    static c_modSecondaryChannelLumScale: number;
    static c_modPrimaryChannelHue: number;
    static c_modPrimaryChannelHueScale: number;
    static c_modPrimaryChannelSat: number;
    static c_modPrimaryChannelSatScale: number;
    static c_modPrimaryChannelLum: number;
    static c_modPrimaryChannelLumScale: number;
    static c_modSecondaryNoteHue: number;
    static c_modSecondaryNoteHueScale: number;
    static c_modSecondaryNoteSat: number;
    static c_modSecondaryNoteSatScale: number;
    static c_modSecondaryNoteLum: number;
    static c_modSecondaryNoteLumScale: number;
    static c_modPrimaryNoteHue: number;
    static c_modPrimaryNoteHueScale: number;
    static c_modPrimaryNoteSat: number;
    static c_modPrimaryNoteSatScale: number;
    static c_modPrimaryNoteLum: number;
    static c_modPrimaryNoteLumScale: number;
    static c_noiseSecondaryChannelHue: number;
    static c_noiseSecondaryChannelHueScale: number;
    static c_noiseSecondaryChannelSat: number;
    static c_noiseSecondaryChannelSatScale: number;
    static c_noiseSecondaryChannelLum: number;
    static c_noiseSecondaryChannelLumScale: number;
    static c_noisePrimaryChannelHue: number;
    static c_noisePrimaryChannelHueScale: number;
    static c_noisePrimaryChannelSat: number;
    static c_noisePrimaryChannelSatScale: number;
    static c_noisePrimaryChannelLum: number;
    static c_noisePrimaryChannelLumScale: number;
    static c_noiseSecondaryNoteHue: number;
    static c_noiseSecondaryNoteHueScale: number;
    static c_noiseSecondaryNoteSat: number;
    static c_noiseSecondaryNoteSatScale: number;
    static c_noiseSecondaryNoteLum: number;
    static c_noiseSecondaryNoteLumScale: number;
    static c_noisePrimaryNoteHue: number;
    static c_noisePrimaryNoteHueScale: number;
    static c_noisePrimaryNoteSat: number;
    static c_noisePrimaryNoteSatScale: number;
    static c_noisePrimaryNoteLum: number;
    static c_noisePrimaryNoteLumScale: number;
    static c_invertedText: string;
    static c_trackEditorBgNoiseDim: string;
    static c_trackEditorBgNoise: string;
    static c_trackEditorBgModDim: string;
    static c_trackEditorBgMod: string;
    static c_trackEditorBgPitchDim: string;
    static c_trackEditorBgPitch: string;
    static readonly pitchChannels: DictionaryArray<ChannelColors>;
    static readonly noiseChannels: DictionaryArray<ChannelColors>;
    static readonly modChannels: DictionaryArray<ChannelColors>;
    static resetColors(): void;
    static getComputedChannelColor(song: Song, channel: number): ChannelColors;
    static getChannelColor(song: Song, channel: number): ChannelColors;
    private static readonly _styleElement;
    static setTheme(name: string): void;
    static getComputed(name: string): string;
}
