import { SongDocument } from "./SongDocument";
import { Prompt } from "./Prompt";
export declare class ExportPrompt implements Prompt {
    private _doc;
    private synth;
    private thenExportTo;
    private recordedSamplesL;
    private recordedSamplesR;
    private sampleFrames;
    private totalChunks;
    private currentChunk;
    private outputStarted;
    private readonly _fileName;
    private readonly _computedSamplesLabel;
    private readonly _enableIntro;
    private readonly _loopDropDown;
    private readonly _enableOutro;
    private readonly _formatSelect;
    private readonly _cancelButton;
    private readonly _exportButton;
    private readonly _outputProgressBar;
    private readonly _outputProgressLabel;
    private readonly _outputProgressContainer;
    private static readonly midiChipInstruments;
    readonly container: HTMLDivElement;
    constructor(_doc: SongDocument);
    private samplesToTime;
    private _close;
    changeFileName(newValue: string): void;
    cleanUp: () => void;
    private _whenKeyPressed;
    private static _validateFileName;
    private static _validateNumber;
    private _export;
    private _synthesize;
    private _exportTo;
    private _exportToWavFinish;
    private _exportToMp3Finish;
    private _exportToMidi;
    private _exportToJson;
    private _exportToHtml;
}
