import { SongDocument } from "./SongDocument";
import { TrackEditor } from "./TrackEditor";
export declare class LoopEditor {
    private _doc;
    private _trackEditor;
    private readonly _editorHeight;
    private readonly _startMode;
    private readonly _endMode;
    private readonly _bothMode;
    private readonly _loopMode;
    private _loopAtPointStart;
    private _loopAtPointEnd;
    private readonly _loop;
    private readonly _barLoop;
    private readonly _highlight;
    private readonly _svg;
    readonly container: HTMLElement;
    private _barWidth;
    private _change;
    private _cursor;
    private _mouseX;
    private _clientStartX;
    private _clientStartY;
    private _startedScrolling;
    private _draggingHorizontally;
    private _mouseDown;
    private _mouseOver;
    private _renderedLoopStart;
    private _renderedLoopStop;
    private _renderedBarCount;
    private _renderedBarWidth;
    private _renderedBarLoopStart;
    private _renderedBarLoopEnd;
    constructor(_doc: SongDocument, _trackEditor: TrackEditor);
    private _updateCursorStatus;
    private _findEndPoints;
    private _whenMouseOver;
    private _whenMouseOut;
    private _whenMousePressed;
    private _whenTouchPressed;
    private _whenMouseMoved;
    private _whenTouchMoved;
    private _whenCursorMoved;
    private _whenTouchReleased;
    private _whenCursorReleased;
    private _updatePreview;
    private _documentChanged;
    setLoopAt(startBar: number, endBar: number): void;
    private _render;
}
