import { SongDocument } from "./SongDocument";
export declare class Piano {
    private _doc;
    private readonly _pianoContainer;
    private readonly _drumContainer;
    private readonly _modContainer;
    private readonly _preview;
    readonly container: HTMLDivElement;
    private readonly _editorHeight;
    private readonly _pianoKeys;
    private readonly _pianoLabels;
    private readonly _modFirstLabels;
    private readonly _modSecondLabels;
    private readonly _modCountLabels;
    private readonly _modCountRects;
    private _pitchHeight;
    private _pitchCount;
    private _mouseY;
    private _mouseDown;
    private _mouseOver;
    private _cursorPitch;
    private _playedPitch;
    private _renderedScale;
    private _renderedDrums;
    private _renderedMod;
    private _renderedKey;
    private _renderedPitchCount;
    private readonly _renderedLiveInputPitches;
    forceRender(): void;
    static getBassCutoffPitch(doc: SongDocument): number;
    constructor(_doc: SongDocument);
    private _updateCursorPitch;
    private _playLiveInput;
    private _releaseLiveInput;
    private _whenMouseOver;
    private _whenMouseOut;
    private _whenMousePressed;
    private _whenMouseMoved;
    private _whenMouseReleased;
    private _whenTouchPressed;
    private _whenTouchMoved;
    private _whenTouchReleased;
    private _onAnimationFrame;
    private _updatePreview;
    private _documentChanged;
    static getPitchName(pitchNameIndex: number, scaleIndex: number, baseVisibleOctave: number): string;
}
