import { BarScrollBar } from "./BarScrollBar";
import "./Layout";
import { Slider } from "./HTMLWrapper";
import { Prompt } from "./Prompt";
import { SongDocument } from "./SongDocument";
export declare class SongEditor {
    private _doc;
    prompt: Prompt | null;
    private readonly _keyboardLayout;
    private readonly _patternEditorPrev;
    private readonly _patternEditor;
    private readonly _patternEditorNext;
    private readonly _trackEditor;
    private readonly _muteEditor;
    private readonly _loopEditor;
    private readonly _piano;
    private readonly _octaveScrollBar;
    private readonly _playButton;
    private readonly _pauseButton;
    private readonly _recordButton;
    private readonly _stopButton;
    private readonly _prevBarButton;
    private readonly _nextBarButton;
    private readonly _volumeSlider;
    private readonly _outVolumeBarBg;
    private readonly _outVolumeBar;
    private readonly _outVolumeCap;
    private readonly _stop1;
    private readonly _stop2;
    private readonly _stop3;
    private readonly _gradient;
    private readonly _defs;
    private readonly _volumeBarContainer;
    private readonly _volumeBarBox;
    private readonly _fileMenu;
    private readonly _editMenu;
    private readonly _optionsMenu;
    private readonly _scaleSelect;
    private readonly _keySelect;
    private readonly _tempoSlider;
    private readonly _tempoStepper;
    private readonly _chorusSlider;
    private readonly _chorusRow;
    private readonly _reverbSlider;
    private readonly _reverbRow;
    private readonly _echoSustainSlider;
    private readonly _echoSustainRow;
    private readonly _echoDelaySlider;
    private readonly _echoDelayRow;
    private readonly _rhythmSelect;
    private readonly _pitchedPresetSelect;
    private readonly _drumPresetSelect;
    private readonly _algorithmSelect;
    private readonly _algorithmSelectRow;
    private readonly _instrumentButtons;
    private readonly _instrumentAddButton;
    private readonly _instrumentRemoveButton;
    private readonly _instrumentsButtonBar;
    private readonly _instrumentsButtonRow;
    private readonly _instrumentVolumeSlider;
    private readonly _instrumentVolumeSliderInputBox;
    private readonly _instrumentVolumeSliderTip;
    private readonly _instrumentVolumeSliderRow;
    private readonly _panSlider;
    private readonly _panDropdown;
    private readonly _panSliderInputBox;
    private readonly _panSliderRow;
    private readonly _panDelaySlider;
    private readonly _panDelayRow;
    private readonly _panDropdownGroup;
    private readonly _chipWaveSelect;
    private readonly _chipNoiseSelect;
    private readonly _chipWaveSelectRow;
    private readonly _chipNoiseSelectRow;
    private readonly _fadeInOutEditor;
    private readonly _fadeInOutRow;
    private readonly _transitionSelect;
    private readonly _transitionDropdown;
    private readonly _transitionRow;
    private readonly _clicklessTransitionBox;
    private readonly _clicklessTransitionRow;
    private readonly _transitionDropdownGroup;
    private readonly _effectsSelect;
    private readonly _eqFilterSimpleButton;
    private readonly _eqFilterAdvancedButton;
    private readonly _eqFilterTypeRow;
    private readonly _eqFilterEditor;
    private readonly _eqFilterZoom;
    private readonly _eqFilterRow;
    private readonly _eqFilterSimpleCutSlider;
    private _eqFilterSimpleCutRow;
    private readonly _eqFilterSimplePeakSlider;
    private _eqFilterSimplePeakRow;
    private readonly _noteFilterSimpleButton;
    private readonly _noteFilterAdvancedButton;
    private readonly _noteFilterTypeRow;
    private readonly _noteFilterEditor;
    private readonly _noteFilterZoom;
    private readonly _noteFilterRow;
    private readonly _supersawDynamismSlider;
    private readonly _supersawDynamismRow;
    private readonly _supersawSpreadSlider;
    private readonly _supersawSpreadRow;
    private readonly _supersawShapeSlider;
    private readonly _supersawShapeRow;
    private readonly _noteFilterSimpleCutSlider;
    private _noteFilterSimpleCutRow;
    private readonly _noteFilterSimplePeakSlider;
    private _noteFilterSimplePeakRow;
    private readonly _pulseWidthSlider;
    private readonly _pwmSliderInputBox;
    private readonly _pulseWidthRow;
    private readonly _pitchShiftSlider;
    private readonly _pitchShiftTonicMarkers;
    private readonly _pitchShiftFifthMarkers;
    private readonly _pitchShiftMarkerContainer;
    private readonly _pitchShiftRow;
    private readonly _detuneSlider;
    private readonly _detuneSliderInputBox;
    private readonly _detuneSliderRow;
    private readonly _distortionSlider;
    private readonly _distortionRow;
    private readonly _aliasingBox;
    private readonly _aliasingRow;
    private readonly _bitcrusherQuantizationSlider;
    private readonly _bitcrusherQuantizationRow;
    private readonly _bitcrusherFreqSlider;
    private readonly _bitcrusherFreqRow;
    private readonly _stringSustainSlider;
    private readonly _stringSustainLabel;
    private readonly _stringSustainRow;
    private readonly _unisonSelect;
    private readonly _unisonSelectRow;
    private readonly _chordSelect;
    private readonly _chordDropdown;
    private readonly _chordSelectRow;
    private readonly _arpeggioSpeedDisplay;
    private readonly _arpeggioSpeedSlider;
    private readonly _arpeggioSpeedRow;
    private readonly _twoNoteArpBox;
    private readonly _twoNoteArpRow;
    private readonly _chordDropdownGroup;
    private readonly _vibratoSelect;
    private readonly _vibratoDropdown;
    private readonly _vibratoSelectRow;
    private readonly _vibratoDepthSlider;
    private readonly _vibratoDepthRow;
    private readonly _vibratoSpeedDisplay;
    private readonly _vibratoSpeedSlider;
    private readonly _vibratoSpeedRow;
    private readonly _vibratoDelaySlider;
    private readonly _vibratoDelayRow;
    private readonly _vibratoTypeSelect;
    private readonly _vibratoTypeSelectRow;
    private readonly _vibratoDropdownGroup;
    private readonly _phaseModGroup;
    private readonly _feedbackTypeSelect;
    private readonly _feedbackRow1;
    private readonly _spectrumEditor;
    private readonly _spectrumRow;
    private readonly _harmonicsEditor;
    private readonly _harmonicsRow;
    private readonly _envelopeEditor;
    private readonly _discreteEnvelopeBox;
    private readonly _discreteEnvelopeRow;
    private readonly _envelopeSpeedDisplay;
    private readonly _envelopeSpeedSlider;
    private readonly _envelopeSpeedRow;
    private readonly _envelopeDropdownGroup;
    private readonly _envelopeDropdown;
    private readonly _drumsetGroup;
    private readonly _modulatorGroup;
    private readonly _modNameRows;
    private readonly _modChannelBoxes;
    private readonly _modInstrumentBoxes;
    private readonly _modSetRows;
    private readonly _modSetBoxes;
    private readonly _modFilterRows;
    private readonly _modFilterBoxes;
    private readonly _modTargetIndicators;
    private readonly _instrumentCopyButton;
    private readonly _instrumentPasteButton;
    private readonly _customWaveDrawCanvas;
    private readonly _customWavePresetDrop;
    private readonly _customWaveZoom;
    private readonly _customWaveDraw;
    private readonly _songTitleInputBox;
    private readonly _feedbackAmplitudeSlider;
    private readonly _feedbackRow2;
    private readonly _addEnvelopeButton;
    private readonly _customInstrumentSettingsGroup;
    private readonly _instrumentCopyGroup;
    private readonly _instrumentSettingsTextRow;
    private readonly _instrumentTypeSelectRow;
    private readonly _instrumentSettingsGroup;
    private readonly _usedPatternIndicator;
    private readonly _usedInstrumentIndicator;
    private readonly _jumpToModIndicator;
    private readonly _promptContainer;
    private readonly _zoomInButton;
    private readonly _zoomOutButton;
    private readonly _patternEditorRow;
    private readonly _patternArea;
    private readonly _trackContainer;
    private readonly _trackVisibleArea;
    private readonly _trackAndMuteContainer;
    readonly _barScrollBar: BarScrollBar;
    private readonly _trackArea;
    private readonly _menuArea;
    private readonly _songSettingsArea;
    private readonly _instrumentSettingsArea;
    readonly _settingsArea: HTMLDivElement;
    readonly mainLayer: HTMLDivElement;
    private _wasPlaying;
    private _currentPromptName;
    private _highlightedInstrumentIndex;
    private _renderedInstrumentCount;
    private _renderedIsPlaying;
    private _renderedIsRecording;
    private _renderedShowRecordButton;
    private _renderedCtrlHeld;
    private _ctrlHeld;
    private _shiftHeld;
    private _deactivatedInstruments;
    private readonly _operatorRows;
    private readonly _operatorAmplitudeSliders;
    private readonly _operatorFrequencySelects;
    private readonly _operatorDropdowns;
    private readonly _operatorWaveformSelects;
    private readonly _operatorWaveformHints;
    private readonly _operatorWaveformPulsewidthSliders;
    private readonly _operatorDropdownRows;
    private readonly _operatorDropdownGroups;
    private readonly _drumsetSpectrumEditors;
    private readonly _drumsetEnvelopeSelects;
    private _showModSliders;
    private _newShowModSliders;
    private _modSliderValues;
    private _hasActiveModSliders;
    private _openPanDropdown;
    private _openVibratoDropdown;
    private _openEnvelopeDropdown;
    private _openChordDropdown;
    private _openTransitionDropdown;
    private _openOperatorDropdowns;
    private outVolumeHistoricTimer;
    private outVolumeHistoricCap;
    private lastOutVolumeCap;
    patternUsed: boolean;
    private _modRecTimeout;
    constructor(_doc: SongDocument);
    private _toggleDropdownMenu;
    private _modSliderUpdate;
    getSliderForModSetting(setting: number): Slider | null;
    private _openPrompt;
    private _setPrompt;
    refocusStage: () => void;
    private _onFocusIn;
    private _refocusStageNotEditing;
    changeBarScrollPos(offset: number): void;
    whenUpdated: () => void;
    handleModRecording(): void;
    private _renderInstrumentBar;
    updatePlayButton: () => void;
    private _onTrackAreaScroll;
    private _disableCtrlContextMenu;
    private _usageCheck;
    private _tempoStepperCaptureNumberKeys;
    private _whenKeyPressed;
    private _whenKeyReleased;
    private _copyTextToClipboard;
    private _whenPrevBarPressed;
    private _whenNextBarPressed;
    togglePlay: () => void;
    private _toggleRecord;
    _animate: () => void;
    _volumeUpdate: () => void;
    private _animateVolume;
    private _setVolumeSlider;
    private _recordVolumeSlider;
    private _copyInstrument;
    private _pasteInstrument;
    private _switchEQFilterType;
    private _switchNoteFilterType;
    private _randomPreset;
    private _randomGenerated;
    private _whenSetTempo;
    private _whenSetScale;
    private _whenSetKey;
    private _whenSetRhythm;
    _refocus: () => void;
    _whenSetPitchedPreset: () => void;
    _whenSetDrumPreset: () => void;
    private _setPreset;
    private _whenSetFeedbackType;
    private _whenSetAlgorithm;
    private _whenSelectInstrument;
    private _whenSetModChannel;
    private _whenSetModInstrument;
    private _whenSetModSetting;
    private _whenClickModTarget;
    private _whenClickJumpToModTarget;
    private _whenSetModFilter;
    private _whenSetChipWave;
    private _whenSetNoiseWave;
    private _whenSetTransition;
    private _whenSetEffects;
    private _whenSetVibrato;
    private _whenSetVibratoType;
    private _whenSetUnison;
    private _whenSetChord;
    private _addNewEnvelope;
    private _zoomIn;
    private _zoomOut;
    private _fileMenuHandler;
    private _editMenuHandler;
    private _optionsMenuHandler;
    private _customWavePresetHandler;
}
