import { SongDocument } from "./SongDocument";
export declare class SongPerformance {
    private _doc;
    private _channelIsDrum;
    private _channelOctave;
    private _songKey;
    private _pitchesAreTemporary;
    private _bassPitchesAreTemporary;
    private readonly _recentlyAddedPitches;
    private readonly _recentlyAddedBassPitches;
    private _songLengthWhenRecordingStarted;
    private _playheadPart;
    private _bassPlayheadPart;
    private _playheadPattern;
    private _bassPlayheadPattern;
    private _pitchesChanged;
    private _bassPitchesChanged;
    private _lastNote;
    private _lastBassNote;
    private _recordingChange;
    constructor(_doc: SongDocument);
    play(): void;
    pause(): void;
    record(): void;
    abortRecording(): void;
    pitchesAreTemporary(): boolean;
    bassPitchesAreTemporary(): boolean;
    private _getBassOffsetChannel;
    private _getMinDivision;
    private _getCurrentPlayheadPart;
    private _lastBarHasPatterns;
    private _onAnimationFrame;
    private _updateRecordedNotes;
    private _updateRecordedBassNotes;
    setTemporaryPitches(pitches: number[], duration: number): void;
    setTemporaryBassPitches(pitches: number[], duration: number): void;
    addPerformedPitch(pitch: number): void;
    removePerformedPitch(pitch: number): void;
    clearAllPitches(): void;
    clearAllBassPitches(): void;
    private _documentChanged;
}
