import { SongDocument } from "./SongDocument";
import { SongEditor } from "./SongEditor";
export declare class TrackEditor {
    private _doc;
    private _songEditor;
    readonly _barDropDown: HTMLSelectElement;
    private readonly _channelRowContainer;
    private readonly _barNumberContainer;
    private readonly _playhead;
    private readonly _boxHighlight;
    private readonly _upHighlight;
    private readonly _downHighlight;
    private readonly _barEditorPath;
    private readonly _selectionRect;
    private readonly _svg;
    private readonly _select;
    readonly container: HTMLElement;
    private readonly _channels;
    private readonly _barNumbers;
    private _mouseX;
    private _mouseY;
    private _mouseStartBar;
    private _mouseStartChannel;
    private _mouseBar;
    private _mouseChannel;
    private _mouseOver;
    private _mousePressed;
    private _mouseDragging;
    private _barWidth;
    private _renderedBarCount;
    private _renderedEditorWidth;
    private _renderedEditorHeight;
    private _renderedPatternCount;
    private _renderedPlayhead;
    private _touchMode;
    private _barDropDownBar;
    private _lastScrollTime;
    constructor(_doc: SongDocument, _songEditor: SongEditor);
    private _barDropDownGetOpenedPosition;
    private _barDropDownHandler;
    private _whenSelectChanged;
    private _animatePlayhead;
    movePlayheadToMouse(): boolean;
    private _dragBoxSelection;
    private _updateSelectPos;
    private _whenSelectPressed;
    private _whenSelectMoved;
    private _whenSelectReleased;
    private _whenMouseOver;
    private _whenMouseOut;
    private _updateMousePos;
    private _whenMousePressed;
    private _whenMouseMoved;
    private _whenMouseReleased;
    private _updatePreview;
    render(): void;
}
